In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

beer = pd.read_csv("https://raw.githubusercontent.com/deeptink/Craft-Beer-Breweries-US-Market-Research/master/Analysis/Data/Beers.csv", sep=',')
beer

                      Name  Beer_ID  ...                           Style  Ounces
0                 Pub Beer     1436  ...             American Pale Lager    12.0
1              Devil's Cup     2265  ...         American Pale Ale (APA)    12.0
2      Rise of the Phoenix     2264  ...                    American IPA    12.0
3                 Sinister     2263  ...  American Double / Imperial IPA    12.0
4            Sex and Candy     2262  ...                    American IPA    12.0
...                    ...      ...  ...                             ...     ...
2405             Belgorado      928  ...                     Belgian IPA    12.0
2406         Rail Yard Ale      807  ...        American Amber / Red Ale    12.0
2407       B3K Black Lager      620  ...                     Schwarzbier    12.0
2408   Silverback Pale Ale      145  ...         American Pale Ale (APA)    12.0
2409  Rail Yard Ale (2009)       84  ...        American Amber / Red Ale    12.0

[2410 rows x 7 columns]

In [2]:
beer.describe()

           Beer_ID          ABV          IBU   Brewery_id       Ounces
count  2410.000000  2348.000000  1405.000000  2410.000000  2410.000000
mean   1431.113278     0.059773    42.713167   232.749793    13.592241
std     752.459975     0.013542    25.954066   157.685604     2.352204
min       1.000000     0.001000     4.000000     1.000000     8.400000
25%     808.250000     0.050000    21.000000    94.000000    12.000000
50%    1453.500000     0.056000    35.000000   206.000000    12.000000
75%    2075.750000     0.067000    64.000000   367.000000    16.000000
max    2692.000000     0.128000   138.000000   558.000000    32.000000

In [3]:
beer[beer['ABV']>=0.06]

                             Name  ...  Ounces
1                     Devil's Cup  ...    12.0
2             Rise of the Phoenix  ...    12.0
3                        Sinister  ...    12.0
4                   Sex and Candy  ...    12.0
5                    Black Exodus  ...    12.0
...                           ...  ...     ...
2399            Worthy IPA (2013)  ...    12.0
2400                  Worthy Pale  ...    12.0
2402    Colorojo Imperial Red Ale  ...    12.0
2404  Rocky Mountain Oyster Stout  ...    12.0
2405                    Belgorado  ...    12.0

[1017 rows x 7 columns]

In [4]:
beer.head(15)

                     Name  Beer_ID  ...                           Style  Ounces
0                Pub Beer     1436  ...             American Pale Lager    12.0
1             Devil's Cup     2265  ...         American Pale Ale (APA)    12.0
2     Rise of the Phoenix     2264  ...                    American IPA    12.0
3                Sinister     2263  ...  American Double / Imperial IPA    12.0
4           Sex and Candy     2262  ...                    American IPA    12.0
5            Black Exodus     2261  ...                   Oatmeal Stout    12.0
6     Lake Street Express     2260  ...         American Pale Ale (APA)    12.0
7                 Foreman     2259  ...                 American Porter    12.0
8                    Jade     2258  ...         American Pale Ale (APA)    12.0
9            Cone Crusher     2131  ...  American Double / Imperial IPA    12.0
10      Sophomoric Saison     2099  ...          Saison / Farmhouse Ale    12.0
11  Regional Ring Of Fire     2098  ...          Saison / Farmhouse Ale    12.0
12             Garce Selé     2097  ...          Saison / Farmhouse Ale    12.0
13        Troll Destroyer     1980  ...                     Belgian IPA    12.0
14           Bitter Bitch     1979  ...         American Pale Ale (APA)    12.0

[15 rows x 7 columns]

In [5]:
Amarga = beer[beer['IBU'] >= 50]
Amarga

                              Name  Beer_ID  ...                    Style  Ounces
14                    Bitter Bitch     1979  ...  American Pale Ale (APA)    12.0
21                   Lower De Boom     1036  ...      American Barleywine     8.4
28       21st Amendment IPA (2006)      799  ...             American IPA    12.0
29    Brew Free! or Die IPA (2008)      797  ...             American IPA    12.0
30    Brew Free! or Die IPA (2009)      796  ...             American IPA    12.0
...                            ...      ...  ...                      ...     ...
2393               4000 Footer IPA     2417  ...             American IPA    12.0
2395                  Be Hoppy IPA     1697  ...             American IPA    16.0
2396                    Worthy IPA     2194  ...             American IPA    12.0
2399             Worthy IPA (2013)     1512  ...             American IPA    12.0
2400                   Worthy Pale     1511  ...  American Pale Ale (APA)    12.0

[491 rows x 7 columns]

Jônatas dos Santos de Sales / Matrícula: 0050015649 / O que mais me chamou atenção foram as diferentes quantidades de teor alcoólico e amargor da cerveja. Sobre o exercício achei bem prático de manipular uma grande quantidade de dados e bem intuitivo com essa plataforma.